/* tslint:disable */
/* eslint-disable */
/**
 * @myorganizer/source
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

/**
 * 
 * @export
 * @interface ConfirmResetPasswordBody
 */
export interface ConfirmResetPasswordBody {
    /**
     * 
     * @type {string}
     * @memberof ConfirmResetPasswordBody
     */
    'token': string;
    /**
     * 
     * @type {string}
     * @memberof ConfirmResetPasswordBody
     */
    'password': string;
    /**
     * 
     * @type {string}
     * @memberof ConfirmResetPasswordBody
     */
    'confirm_password': string;
}
/**
 * 
 * @export
 * @interface EncryptedBlobV1
 */
export interface EncryptedBlobV1 {
    [key: string]: any;

    /**
     * 
     * @type {number}
     * @memberof EncryptedBlobV1
     */
    'version': number;
    /**
     * 
     * @type {string}
     * @memberof EncryptedBlobV1
     */
    'iv': string;
    /**
     * 
     * @type {string}
     * @memberof EncryptedBlobV1
     */
    'ciphertext': string;
}
/**
 * 
 * @export
 * @interface ErrorResponse
 */
export interface ErrorResponse {
    /**
     * 
     * @type {any}
     * @memberof ErrorResponse
     */
    'details'?: any;
    /**
     * 
     * @type {string}
     * @memberof ErrorResponse
     */
    'message': string;
}
/**
 * 
 * @export
 * @interface ExportVaultResponse
 */
export interface ExportVaultResponse {
    /**
     * 
     * @type {number}
     * @memberof ExportVaultResponse
     */
    'exportVersion': ExportVaultResponseExportVersionEnum;
    /**
     * 
     * @type {string}
     * @memberof ExportVaultResponse
     */
    'exportedAt': string;
    /**
     * 
     * @type {VaultMetaV1}
     * @memberof ExportVaultResponse
     */
    'meta': VaultMetaV1;
    /**
     * 
     * @type {PartialRecordVaultBlobTypeEncryptedBlobV1}
     * @memberof ExportVaultResponse
     */
    'blobs': PartialRecordVaultBlobTypeEncryptedBlobV1;
    /**
     * 
     * @type {any}
     * @memberof ExportVaultResponse
     */
    'details'?: any;
    /**
     * 
     * @type {string}
     * @memberof ExportVaultResponse
     */
    'message': string;
}

export const ExportVaultResponseExportVersionEnum = {
    NUMBER_1: 1
} as const;

export type ExportVaultResponseExportVersionEnum = typeof ExportVaultResponseExportVersionEnum[keyof typeof ExportVaultResponseExportVersionEnum];

/**
 * 
 * @export
 * @interface FilteredUserInterface
 */
export interface FilteredUserInterface {
    /**
     * 
     * @type {string}
     * @memberof FilteredUserInterface
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof FilteredUserInterface
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof FilteredUserInterface
     */
    'email': string;
    /**
     * 
     * @type {string}
     * @memberof FilteredUserInterface
     */
    'firstName': string;
    /**
     * 
     * @type {string}
     * @memberof FilteredUserInterface
     */
    'lastName': string;
    /**
     * 
     * @type {string}
     * @memberof FilteredUserInterface
     */
    'phone'?: string;
}
/**
 * 
 * @export
 * @interface GetVaultBlobResponse
 */
export interface GetVaultBlobResponse {
    /**
     * 
     * @type {string}
     * @memberof GetVaultBlobResponse
     */
    'etag': string;
    /**
     * 
     * @type {string}
     * @memberof GetVaultBlobResponse
     */
    'updatedAt': string;
    /**
     * 
     * @type {EncryptedBlobV1}
     * @memberof GetVaultBlobResponse
     */
    'blob': EncryptedBlobV1;
    /**
     * 
     * @type {VaultBlobType}
     * @memberof GetVaultBlobResponse
     */
    'type': VaultBlobType;
    /**
     * 
     * @type {any}
     * @memberof GetVaultBlobResponse
     */
    'details'?: any;
    /**
     * 
     * @type {string}
     * @memberof GetVaultBlobResponse
     */
    'message': string;
}


/**
 * 
 * @export
 * @interface GetVaultBlobResponseAnyOf
 */
export interface GetVaultBlobResponseAnyOf {
    /**
     * 
     * @type {string}
     * @memberof GetVaultBlobResponseAnyOf
     */
    'etag': string;
    /**
     * 
     * @type {string}
     * @memberof GetVaultBlobResponseAnyOf
     */
    'updatedAt': string;
    /**
     * 
     * @type {EncryptedBlobV1}
     * @memberof GetVaultBlobResponseAnyOf
     */
    'blob': EncryptedBlobV1;
    /**
     * 
     * @type {VaultBlobType}
     * @memberof GetVaultBlobResponseAnyOf
     */
    'type': VaultBlobType;
}


/**
 * 
 * @export
 * @interface GetVaultMetaResponse
 */
export interface GetVaultMetaResponse {
    /**
     * 
     * @type {string}
     * @memberof GetVaultMetaResponse
     */
    'etag': string;
    /**
     * 
     * @type {string}
     * @memberof GetVaultMetaResponse
     */
    'updatedAt': string;
    /**
     * 
     * @type {VaultMetaV1}
     * @memberof GetVaultMetaResponse
     */
    'meta': VaultMetaV1;
    /**
     * 
     * @type {any}
     * @memberof GetVaultMetaResponse
     */
    'details'?: any;
    /**
     * 
     * @type {string}
     * @memberof GetVaultMetaResponse
     */
    'message': string;
}
/**
 * 
 * @export
 * @interface GetVaultMetaResponseAnyOf
 */
export interface GetVaultMetaResponseAnyOf {
    /**
     * 
     * @type {string}
     * @memberof GetVaultMetaResponseAnyOf
     */
    'etag': string;
    /**
     * 
     * @type {string}
     * @memberof GetVaultMetaResponseAnyOf
     */
    'updatedAt': string;
    /**
     * 
     * @type {VaultMetaV1}
     * @memberof GetVaultMetaResponseAnyOf
     */
    'meta': VaultMetaV1;
}
/**
 * 
 * @export
 * @interface ImportVaultResponse
 */
export interface ImportVaultResponse {
    /**
     * 
     * @type {boolean}
     * @memberof ImportVaultResponse
     */
    'ok': boolean;
    /**
     * 
     * @type {any}
     * @memberof ImportVaultResponse
     */
    'details'?: any;
    /**
     * 
     * @type {string}
     * @memberof ImportVaultResponse
     */
    'message': string;
}
/**
 * 
 * @export
 * @interface ImportVaultResponseAnyOf
 */
export interface ImportVaultResponseAnyOf {
    /**
     * 
     * @type {boolean}
     * @memberof ImportVaultResponseAnyOf
     */
    'ok': boolean;
}
/**
 * 
 * @export
 * @interface Login200Response
 */
export interface Login200Response {
    /**
     * 
     * @type {FilteredUserInterface}
     * @memberof Login200Response
     */
    'user': FilteredUserInterface;
    /**
     * 
     * @type {number}
     * @memberof Login200Response
     */
    'expires_in': number;
    /**
     * 
     * @type {string}
     * @memberof Login200Response
     */
    'token': string;
}
/**
 * 
 * @export
 * @interface Logout200Response
 */
export interface Logout200Response {
    /**
     * 
     * @type {string}
     * @memberof Logout200Response
     */
    'message': string;
}
/**
 * Make all properties in T optional
 * @export
 * @interface PartialRecordVaultBlobTypeEncryptedBlobV1
 */
export interface PartialRecordVaultBlobTypeEncryptedBlobV1 {
    /**
     * 
     * @type {EncryptedBlobV1}
     * @memberof PartialRecordVaultBlobTypeEncryptedBlobV1
     */
    'addresses'?: EncryptedBlobV1;
    /**
     * 
     * @type {EncryptedBlobV1}
     * @memberof PartialRecordVaultBlobTypeEncryptedBlobV1
     */
    'mobileNumbers'?: EncryptedBlobV1;
    /**
     * 
     * @type {EncryptedBlobV1}
     * @memberof PartialRecordVaultBlobTypeEncryptedBlobV1
     */
    'subscriptions'?: EncryptedBlobV1;
    /**
     * 
     * @type {EncryptedBlobV1}
     * @memberof PartialRecordVaultBlobTypeEncryptedBlobV1
     */
    'todos'?: EncryptedBlobV1;
}
/**
 * 
 * @export
 * @interface PutVaultBlobRequest
 */
export interface PutVaultBlobRequest {
    /**
     * 
     * @type {EncryptedBlobV1}
     * @memberof PutVaultBlobRequest
     */
    'blob': EncryptedBlobV1;
    /**
     * 
     * @type {VaultBlobType}
     * @memberof PutVaultBlobRequest
     */
    'type': VaultBlobType;
}


/**
 * 
 * @export
 * @interface PutVaultBlobResponse
 */
export interface PutVaultBlobResponse {
    /**
     * 
     * @type {string}
     * @memberof PutVaultBlobResponse
     */
    'updatedAt': string;
    /**
     * 
     * @type {string}
     * @memberof PutVaultBlobResponse
     */
    'etag': string;
    /**
     * 
     * @type {boolean}
     * @memberof PutVaultBlobResponse
     */
    'ok': boolean;
    /**
     * 
     * @type {any}
     * @memberof PutVaultBlobResponse
     */
    'details'?: any;
    /**
     * 
     * @type {string}
     * @memberof PutVaultBlobResponse
     */
    'message': string;
}
/**
 * 
 * @export
 * @interface PutVaultMetaRequest
 */
export interface PutVaultMetaRequest {
    /**
     * 
     * @type {VaultMetaV1}
     * @memberof PutVaultMetaRequest
     */
    'meta': VaultMetaV1;
}
/**
 * 
 * @export
 * @interface PutVaultMetaResponse
 */
export interface PutVaultMetaResponse {
    /**
     * 
     * @type {string}
     * @memberof PutVaultMetaResponse
     */
    'updatedAt': string;
    /**
     * 
     * @type {string}
     * @memberof PutVaultMetaResponse
     */
    'etag': string;
    /**
     * 
     * @type {boolean}
     * @memberof PutVaultMetaResponse
     */
    'ok': boolean;
    /**
     * 
     * @type {any}
     * @memberof PutVaultMetaResponse
     */
    'details'?: any;
    /**
     * 
     * @type {string}
     * @memberof PutVaultMetaResponse
     */
    'message': string;
}
/**
 * 
 * @export
 * @interface PutVaultMetaResponseAnyOf
 */
export interface PutVaultMetaResponseAnyOf {
    /**
     * 
     * @type {string}
     * @memberof PutVaultMetaResponseAnyOf
     */
    'updatedAt': string;
    /**
     * 
     * @type {string}
     * @memberof PutVaultMetaResponseAnyOf
     */
    'etag': string;
    /**
     * 
     * @type {boolean}
     * @memberof PutVaultMetaResponseAnyOf
     */
    'ok': boolean;
}
/**
 * 
 * @export
 * @interface RefreshTokenRequest
 */
export interface RefreshTokenRequest {
    /**
     * 
     * @type {string}
     * @memberof RefreshTokenRequest
     */
    'refresh_token'?: string;
}
/**
 * 
 * @export
 * @interface RegisterUserResponse
 */
export interface RegisterUserResponse {
    /**
     * 
     * @type {string}
     * @memberof RegisterUserResponse
     */
    'message': string;
    /**
     * 
     * @type {FilteredUserInterface}
     * @memberof RegisterUserResponse
     */
    'user'?: FilteredUserInterface;
}
/**
 * 
 * @export
 * @interface ResendVerificationEmailByEmail200Response
 */
export interface ResendVerificationEmailByEmail200Response {
    /**
     * 
     * @type {string}
     * @memberof ResendVerificationEmailByEmail200Response
     */
    'message': string;
    /**
     * 
     * @type {number}
     * @memberof ResendVerificationEmailByEmail200Response
     */
    'status': number;
}
/**
 * 
 * @export
 * @interface ResendVerificationEmailByEmailRequest
 */
export interface ResendVerificationEmailByEmailRequest {
    /**
     * 
     * @type {string}
     * @memberof ResendVerificationEmailByEmailRequest
     */
    'email': string;
}
/**
 * 
 * @export
 * @interface ResetPasswordByEmailBody
 */
export interface ResetPasswordByEmailBody {
    /**
     * 
     * @type {string}
     * @memberof ResetPasswordByEmailBody
     */
    'email': string;
}
/**
 * 
 * @export
 * @interface User
 */
export interface User {
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'first_name'?: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'last_name'?: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'phone'?: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'email': string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'password'?: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'reset_password_token'?: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'email_verification_timestamp'?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof User
     */
    'blacklisted_tokens'?: Array<string>;
}
/**
 * 
 * @export
 * @interface UserCreationBody
 */
export interface UserCreationBody {
    /**
     * 
     * @type {string}
     * @memberof UserCreationBody
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof UserCreationBody
     */
    'firstName': string;
    /**
     * 
     * @type {string}
     * @memberof UserCreationBody
     */
    'lastName': string;
    /**
     * 
     * @type {string}
     * @memberof UserCreationBody
     */
    'phone'?: string;
    /**
     * 
     * @type {string}
     * @memberof UserCreationBody
     */
    'email': string;
    /**
     * 
     * @type {string}
     * @memberof UserCreationBody
     */
    'password': string;
}
/**
 * 
 * @export
 * @interface UserLoginBody
 */
export interface UserLoginBody {
    /**
     * 
     * @type {string}
     * @memberof UserLoginBody
     */
    'email': string;
    /**
     * 
     * @type {string}
     * @memberof UserLoginBody
     */
    'password': string;
}
/**
 * 
 * @export
 * @interface ValidateErrorJSON
 */
export interface ValidateErrorJSON {
    /**
     * 
     * @type {string}
     * @memberof ValidateErrorJSON
     */
    'message': ValidateErrorJSONMessageEnum;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof ValidateErrorJSON
     */
    'details': { [key: string]: any; };
}

export const ValidateErrorJSONMessageEnum = {
    ValidationFailed: 'Validation failed'
} as const;

export type ValidateErrorJSONMessageEnum = typeof ValidateErrorJSONMessageEnum[keyof typeof ValidateErrorJSONMessageEnum];

/**
 * 
 * @export
 * @enum {string}
 */

export const VaultBlobType = {
    Addresses: 'addresses',
    MobileNumbers: 'mobileNumbers',
    Subscriptions: 'subscriptions',
    Todos: 'todos'
} as const;

export type VaultBlobType = typeof VaultBlobType[keyof typeof VaultBlobType];


/**
 * 
 * @export
 * @interface VaultExportV1
 */
export interface VaultExportV1 {
    /**
     * 
     * @type {number}
     * @memberof VaultExportV1
     */
    'exportVersion': VaultExportV1ExportVersionEnum;
    /**
     * 
     * @type {string}
     * @memberof VaultExportV1
     */
    'exportedAt': string;
    /**
     * 
     * @type {VaultMetaV1}
     * @memberof VaultExportV1
     */
    'meta': VaultMetaV1;
    /**
     * 
     * @type {PartialRecordVaultBlobTypeEncryptedBlobV1}
     * @memberof VaultExportV1
     */
    'blobs': PartialRecordVaultBlobTypeEncryptedBlobV1;
}

export const VaultExportV1ExportVersionEnum = {
    NUMBER_1: 1
} as const;

export type VaultExportV1ExportVersionEnum = typeof VaultExportV1ExportVersionEnum[keyof typeof VaultExportV1ExportVersionEnum];

/**
 * 
 * @export
 * @interface VaultMetaV1
 */
export interface VaultMetaV1 {
    [key: string]: any;

    /**
     * 
     * @type {number}
     * @memberof VaultMetaV1
     */
    'version': number;
    /**
     * 
     * @type {string}
     * @memberof VaultMetaV1
     */
    'kdf_name': string;
    /**
     * 
     * @type {string}
     * @memberof VaultMetaV1
     */
    'kdf_salt': string;
    /**
     * Construct a type with a set of properties K of type T
     * @type {{ [key: string]: any; }}
     * @memberof VaultMetaV1
     */
    'kdf_params': { [key: string]: any; };
    /**
     * 
     * @type {any}
     * @memberof VaultMetaV1
     */
    'wrapped_mk_passphrase': any;
    /**
     * 
     * @type {any}
     * @memberof VaultMetaV1
     */
    'wrapped_mk_recovery': any;
}
/**
 * 
 * @export
 * @interface VerifyEmailRequest
 */
export interface VerifyEmailRequest {
    /**
     * 
     * @type {string}
     * @memberof VerifyEmailRequest
     */
    'token': string;
}

/**
 * AuthenticationApi - axios parameter creator
 * @export
 */
export const AuthenticationApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {ConfirmResetPasswordBody} confirmResetPasswordBody 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        confirmResetPassword: async (confirmResetPasswordBody: ConfirmResetPasswordBody, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'confirmResetPasswordBody' is not null or undefined
            assertParamExists('confirmResetPassword', 'confirmResetPasswordBody', confirmResetPasswordBody)
            const localVarPath = `/auth/password/reset/confirm`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(confirmResetPasswordBody, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {UserLoginBody} userLoginBody 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        login: async (userLoginBody: UserLoginBody, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'userLoginBody' is not null or undefined
            assertParamExists('login', 'userLoginBody', userLoginBody)
            const localVarPath = `/auth/login`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(userLoginBody, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} userId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        logout: async (userId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'userId' is not null or undefined
            assertParamExists('logout', 'userId', userId)
            const localVarPath = `/auth/logout/{userId}`
                .replace(`{${"userId"}}`, encodeURIComponent(String(userId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication jwt required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {RefreshTokenRequest} [refreshTokenRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        refreshToken: async (refreshTokenRequest?: RefreshTokenRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/auth/refresh`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(refreshTokenRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {UserCreationBody} userCreationBody 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        registerUser: async (userCreationBody: UserCreationBody, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'userCreationBody' is not null or undefined
            assertParamExists('registerUser', 'userCreationBody', userCreationBody)
            const localVarPath = `/auth/register`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(userCreationBody, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} userId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        resendVerificationEmail: async (userId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'userId' is not null or undefined
            assertParamExists('resendVerificationEmail', 'userId', userId)
            const localVarPath = `/auth/verify/resend/{userId}`
                .replace(`{${"userId"}}`, encodeURIComponent(String(userId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication jwt required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {ResendVerificationEmailByEmailRequest} resendVerificationEmailByEmailRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        resendVerificationEmailByEmail: async (resendVerificationEmailByEmailRequest: ResendVerificationEmailByEmailRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'resendVerificationEmailByEmailRequest' is not null or undefined
            assertParamExists('resendVerificationEmailByEmail', 'resendVerificationEmailByEmailRequest', resendVerificationEmailByEmailRequest)
            const localVarPath = `/auth/verify/resend`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(resendVerificationEmailByEmailRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {ResetPasswordByEmailBody} resetPasswordByEmailBody 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        resetPassword: async (resetPasswordByEmailBody: ResetPasswordByEmailBody, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'resetPasswordByEmailBody' is not null or undefined
            assertParamExists('resetPassword', 'resetPasswordByEmailBody', resetPasswordByEmailBody)
            const localVarPath = `/auth/password/reset`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(resetPasswordByEmailBody, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {VerifyEmailRequest} verifyEmailRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        verifyEmail: async (verifyEmailRequest: VerifyEmailRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'verifyEmailRequest' is not null or undefined
            assertParamExists('verifyEmail', 'verifyEmailRequest', verifyEmailRequest)
            const localVarPath = `/auth/verify/email`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(verifyEmailRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AuthenticationApi - functional programming interface
 * @export
 */
export const AuthenticationApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AuthenticationApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {ConfirmResetPasswordBody} confirmResetPasswordBody 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async confirmResetPassword(confirmResetPasswordBody: ConfirmResetPasswordBody, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ResendVerificationEmailByEmail200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.confirmResetPassword(confirmResetPasswordBody, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthenticationApi.confirmResetPassword']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {UserLoginBody} userLoginBody 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async login(userLoginBody: UserLoginBody, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Login200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.login(userLoginBody, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthenticationApi.login']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} userId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async logout(userId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Logout200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.logout(userId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthenticationApi.logout']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {RefreshTokenRequest} [refreshTokenRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async refreshToken(refreshTokenRequest?: RefreshTokenRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Login200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.refreshToken(refreshTokenRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthenticationApi.refreshToken']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {UserCreationBody} userCreationBody 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async registerUser(userCreationBody: UserCreationBody, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<RegisterUserResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.registerUser(userCreationBody, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthenticationApi.registerUser']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} userId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async resendVerificationEmail(userId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.resendVerificationEmail(userId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthenticationApi.resendVerificationEmail']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {ResendVerificationEmailByEmailRequest} resendVerificationEmailByEmailRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async resendVerificationEmailByEmail(resendVerificationEmailByEmailRequest: ResendVerificationEmailByEmailRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ResendVerificationEmailByEmail200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.resendVerificationEmailByEmail(resendVerificationEmailByEmailRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthenticationApi.resendVerificationEmailByEmail']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {ResetPasswordByEmailBody} resetPasswordByEmailBody 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async resetPassword(resetPasswordByEmailBody: ResetPasswordByEmailBody, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ResendVerificationEmailByEmail200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.resetPassword(resetPasswordByEmailBody, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthenticationApi.resetPassword']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {VerifyEmailRequest} verifyEmailRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async verifyEmail(verifyEmailRequest: VerifyEmailRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<FilteredUserInterface>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.verifyEmail(verifyEmailRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthenticationApi.verifyEmail']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * AuthenticationApi - factory interface
 * @export
 */
export const AuthenticationApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AuthenticationApiFp(configuration)
    return {
        /**
         * 
         * @param {AuthenticationApiConfirmResetPasswordRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        confirmResetPassword(requestParameters: AuthenticationApiConfirmResetPasswordRequest, options?: RawAxiosRequestConfig): AxiosPromise<ResendVerificationEmailByEmail200Response> {
            return localVarFp.confirmResetPassword(requestParameters.confirmResetPasswordBody, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {AuthenticationApiLoginRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        login(requestParameters: AuthenticationApiLoginRequest, options?: RawAxiosRequestConfig): AxiosPromise<Login200Response> {
            return localVarFp.login(requestParameters.userLoginBody, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {AuthenticationApiLogoutRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        logout(requestParameters: AuthenticationApiLogoutRequest, options?: RawAxiosRequestConfig): AxiosPromise<Logout200Response> {
            return localVarFp.logout(requestParameters.userId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {AuthenticationApiRefreshTokenRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        refreshToken(requestParameters: AuthenticationApiRefreshTokenRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<Login200Response> {
            return localVarFp.refreshToken(requestParameters.refreshTokenRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {AuthenticationApiRegisterUserRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        registerUser(requestParameters: AuthenticationApiRegisterUserRequest, options?: RawAxiosRequestConfig): AxiosPromise<RegisterUserResponse> {
            return localVarFp.registerUser(requestParameters.userCreationBody, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {AuthenticationApiResendVerificationEmailRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        resendVerificationEmail(requestParameters: AuthenticationApiResendVerificationEmailRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.resendVerificationEmail(requestParameters.userId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {AuthenticationApiResendVerificationEmailByEmailRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        resendVerificationEmailByEmail(requestParameters: AuthenticationApiResendVerificationEmailByEmailRequest, options?: RawAxiosRequestConfig): AxiosPromise<ResendVerificationEmailByEmail200Response> {
            return localVarFp.resendVerificationEmailByEmail(requestParameters.resendVerificationEmailByEmailRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {AuthenticationApiResetPasswordRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        resetPassword(requestParameters: AuthenticationApiResetPasswordRequest, options?: RawAxiosRequestConfig): AxiosPromise<ResendVerificationEmailByEmail200Response> {
            return localVarFp.resetPassword(requestParameters.resetPasswordByEmailBody, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {AuthenticationApiVerifyEmailRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        verifyEmail(requestParameters: AuthenticationApiVerifyEmailRequest, options?: RawAxiosRequestConfig): AxiosPromise<FilteredUserInterface> {
            return localVarFp.verifyEmail(requestParameters.verifyEmailRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for confirmResetPassword operation in AuthenticationApi.
 * @export
 * @interface AuthenticationApiConfirmResetPasswordRequest
 */
export interface AuthenticationApiConfirmResetPasswordRequest {
    /**
     * 
     * @type {ConfirmResetPasswordBody}
     * @memberof AuthenticationApiConfirmResetPassword
     */
    readonly confirmResetPasswordBody: ConfirmResetPasswordBody
}

/**
 * Request parameters for login operation in AuthenticationApi.
 * @export
 * @interface AuthenticationApiLoginRequest
 */
export interface AuthenticationApiLoginRequest {
    /**
     * 
     * @type {UserLoginBody}
     * @memberof AuthenticationApiLogin
     */
    readonly userLoginBody: UserLoginBody
}

/**
 * Request parameters for logout operation in AuthenticationApi.
 * @export
 * @interface AuthenticationApiLogoutRequest
 */
export interface AuthenticationApiLogoutRequest {
    /**
     * 
     * @type {string}
     * @memberof AuthenticationApiLogout
     */
    readonly userId: string
}

/**
 * Request parameters for refreshToken operation in AuthenticationApi.
 * @export
 * @interface AuthenticationApiRefreshTokenRequest
 */
export interface AuthenticationApiRefreshTokenRequest {
    /**
     * 
     * @type {RefreshTokenRequest}
     * @memberof AuthenticationApiRefreshToken
     */
    readonly refreshTokenRequest?: RefreshTokenRequest
}

/**
 * Request parameters for registerUser operation in AuthenticationApi.
 * @export
 * @interface AuthenticationApiRegisterUserRequest
 */
export interface AuthenticationApiRegisterUserRequest {
    /**
     * 
     * @type {UserCreationBody}
     * @memberof AuthenticationApiRegisterUser
     */
    readonly userCreationBody: UserCreationBody
}

/**
 * Request parameters for resendVerificationEmail operation in AuthenticationApi.
 * @export
 * @interface AuthenticationApiResendVerificationEmailRequest
 */
export interface AuthenticationApiResendVerificationEmailRequest {
    /**
     * 
     * @type {string}
     * @memberof AuthenticationApiResendVerificationEmail
     */
    readonly userId: string
}

/**
 * Request parameters for resendVerificationEmailByEmail operation in AuthenticationApi.
 * @export
 * @interface AuthenticationApiResendVerificationEmailByEmailRequest
 */
export interface AuthenticationApiResendVerificationEmailByEmailRequest {
    /**
     * 
     * @type {ResendVerificationEmailByEmailRequest}
     * @memberof AuthenticationApiResendVerificationEmailByEmail
     */
    readonly resendVerificationEmailByEmailRequest: ResendVerificationEmailByEmailRequest
}

/**
 * Request parameters for resetPassword operation in AuthenticationApi.
 * @export
 * @interface AuthenticationApiResetPasswordRequest
 */
export interface AuthenticationApiResetPasswordRequest {
    /**
     * 
     * @type {ResetPasswordByEmailBody}
     * @memberof AuthenticationApiResetPassword
     */
    readonly resetPasswordByEmailBody: ResetPasswordByEmailBody
}

/**
 * Request parameters for verifyEmail operation in AuthenticationApi.
 * @export
 * @interface AuthenticationApiVerifyEmailRequest
 */
export interface AuthenticationApiVerifyEmailRequest {
    /**
     * 
     * @type {VerifyEmailRequest}
     * @memberof AuthenticationApiVerifyEmail
     */
    readonly verifyEmailRequest: VerifyEmailRequest
}

/**
 * AuthenticationApi - object-oriented interface
 * @export
 * @class AuthenticationApi
 * @extends {BaseAPI}
 */
export class AuthenticationApi extends BaseAPI {
    /**
     * 
     * @param {AuthenticationApiConfirmResetPasswordRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthenticationApi
     */
    public confirmResetPassword(requestParameters: AuthenticationApiConfirmResetPasswordRequest, options?: RawAxiosRequestConfig) {
        return AuthenticationApiFp(this.configuration).confirmResetPassword(requestParameters.confirmResetPasswordBody, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {AuthenticationApiLoginRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthenticationApi
     */
    public login(requestParameters: AuthenticationApiLoginRequest, options?: RawAxiosRequestConfig) {
        return AuthenticationApiFp(this.configuration).login(requestParameters.userLoginBody, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {AuthenticationApiLogoutRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthenticationApi
     */
    public logout(requestParameters: AuthenticationApiLogoutRequest, options?: RawAxiosRequestConfig) {
        return AuthenticationApiFp(this.configuration).logout(requestParameters.userId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {AuthenticationApiRefreshTokenRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthenticationApi
     */
    public refreshToken(requestParameters: AuthenticationApiRefreshTokenRequest = {}, options?: RawAxiosRequestConfig) {
        return AuthenticationApiFp(this.configuration).refreshToken(requestParameters.refreshTokenRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {AuthenticationApiRegisterUserRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthenticationApi
     */
    public registerUser(requestParameters: AuthenticationApiRegisterUserRequest, options?: RawAxiosRequestConfig) {
        return AuthenticationApiFp(this.configuration).registerUser(requestParameters.userCreationBody, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {AuthenticationApiResendVerificationEmailRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthenticationApi
     */
    public resendVerificationEmail(requestParameters: AuthenticationApiResendVerificationEmailRequest, options?: RawAxiosRequestConfig) {
        return AuthenticationApiFp(this.configuration).resendVerificationEmail(requestParameters.userId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {AuthenticationApiResendVerificationEmailByEmailRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthenticationApi
     */
    public resendVerificationEmailByEmail(requestParameters: AuthenticationApiResendVerificationEmailByEmailRequest, options?: RawAxiosRequestConfig) {
        return AuthenticationApiFp(this.configuration).resendVerificationEmailByEmail(requestParameters.resendVerificationEmailByEmailRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {AuthenticationApiResetPasswordRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthenticationApi
     */
    public resetPassword(requestParameters: AuthenticationApiResetPasswordRequest, options?: RawAxiosRequestConfig) {
        return AuthenticationApiFp(this.configuration).resetPassword(requestParameters.resetPasswordByEmailBody, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {AuthenticationApiVerifyEmailRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthenticationApi
     */
    public verifyEmail(requestParameters: AuthenticationApiVerifyEmailRequest, options?: RawAxiosRequestConfig) {
        return AuthenticationApiFp(this.configuration).verifyEmail(requestParameters.verifyEmailRequest, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * UsersManagementApi - axios parameter creator
 * @export
 */
export const UsersManagementApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {UserCreationBody} userCreationBody 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createUser: async (userCreationBody: UserCreationBody, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'userCreationBody' is not null or undefined
            assertParamExists('createUser', 'userCreationBody', userCreationBody)
            const localVarPath = `/user`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(userCreationBody, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllUsers: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/user`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication jwt required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} userId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUserById: async (userId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'userId' is not null or undefined
            assertParamExists('getUserById', 'userId', userId)
            const localVarPath = `/user/{userId}`
                .replace(`{${"userId"}}`, encodeURIComponent(String(userId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * UsersManagementApi - functional programming interface
 * @export
 */
export const UsersManagementApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = UsersManagementApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {UserCreationBody} userCreationBody 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createUser(userCreationBody: UserCreationBody, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<FilteredUserInterface>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createUser(userCreationBody, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UsersManagementApi.createUser']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAllUsers(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<User>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getAllUsers(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UsersManagementApi.getAllUsers']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} userId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getUserById(userId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<User>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getUserById(userId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UsersManagementApi.getUserById']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * UsersManagementApi - factory interface
 * @export
 */
export const UsersManagementApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = UsersManagementApiFp(configuration)
    return {
        /**
         * 
         * @param {UsersManagementApiCreateUserRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createUser(requestParameters: UsersManagementApiCreateUserRequest, options?: RawAxiosRequestConfig): AxiosPromise<FilteredUserInterface> {
            return localVarFp.createUser(requestParameters.userCreationBody, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllUsers(options?: RawAxiosRequestConfig): AxiosPromise<Array<User>> {
            return localVarFp.getAllUsers(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {UsersManagementApiGetUserByIdRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUserById(requestParameters: UsersManagementApiGetUserByIdRequest, options?: RawAxiosRequestConfig): AxiosPromise<User> {
            return localVarFp.getUserById(requestParameters.userId, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for createUser operation in UsersManagementApi.
 * @export
 * @interface UsersManagementApiCreateUserRequest
 */
export interface UsersManagementApiCreateUserRequest {
    /**
     * 
     * @type {UserCreationBody}
     * @memberof UsersManagementApiCreateUser
     */
    readonly userCreationBody: UserCreationBody
}

/**
 * Request parameters for getUserById operation in UsersManagementApi.
 * @export
 * @interface UsersManagementApiGetUserByIdRequest
 */
export interface UsersManagementApiGetUserByIdRequest {
    /**
     * 
     * @type {string}
     * @memberof UsersManagementApiGetUserById
     */
    readonly userId: string
}

/**
 * UsersManagementApi - object-oriented interface
 * @export
 * @class UsersManagementApi
 * @extends {BaseAPI}
 */
export class UsersManagementApi extends BaseAPI {
    /**
     * 
     * @param {UsersManagementApiCreateUserRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UsersManagementApi
     */
    public createUser(requestParameters: UsersManagementApiCreateUserRequest, options?: RawAxiosRequestConfig) {
        return UsersManagementApiFp(this.configuration).createUser(requestParameters.userCreationBody, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UsersManagementApi
     */
    public getAllUsers(options?: RawAxiosRequestConfig) {
        return UsersManagementApiFp(this.configuration).getAllUsers(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {UsersManagementApiGetUserByIdRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UsersManagementApi
     */
    public getUserById(requestParameters: UsersManagementApiGetUserByIdRequest, options?: RawAxiosRequestConfig) {
        return UsersManagementApiFp(this.configuration).getUserById(requestParameters.userId, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * VaultApi - axios parameter creator
 * @export
 */
export const VaultApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        exportVault: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/vault/export`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication jwt required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {VaultBlobType} type 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getVaultBlob: async (type: VaultBlobType, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'type' is not null or undefined
            assertParamExists('getVaultBlob', 'type', type)
            const localVarPath = `/vault/blob/{type}`
                .replace(`{${"type"}}`, encodeURIComponent(String(type)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication jwt required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getVaultMeta: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/vault`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication jwt required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {VaultExportV1} vaultExportV1 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        importVault: async (vaultExportV1: VaultExportV1, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'vaultExportV1' is not null or undefined
            assertParamExists('importVault', 'vaultExportV1', vaultExportV1)
            const localVarPath = `/vault/import`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication jwt required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(vaultExportV1, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {VaultBlobType} type 
         * @param {PutVaultBlobRequest} putVaultBlobRequest 
         * @param {string} [ifMatch] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        putVaultBlob: async (type: VaultBlobType, putVaultBlobRequest: PutVaultBlobRequest, ifMatch?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'type' is not null or undefined
            assertParamExists('putVaultBlob', 'type', type)
            // verify required parameter 'putVaultBlobRequest' is not null or undefined
            assertParamExists('putVaultBlob', 'putVaultBlobRequest', putVaultBlobRequest)
            const localVarPath = `/vault/blob/{type}`
                .replace(`{${"type"}}`, encodeURIComponent(String(type)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication jwt required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            if (ifMatch != null) {
                localVarHeaderParameter['if-match'] = String(ifMatch);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(putVaultBlobRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {PutVaultMetaRequest} putVaultMetaRequest 
         * @param {string} [ifMatch] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        putVaultMeta: async (putVaultMetaRequest: PutVaultMetaRequest, ifMatch?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'putVaultMetaRequest' is not null or undefined
            assertParamExists('putVaultMeta', 'putVaultMetaRequest', putVaultMetaRequest)
            const localVarPath = `/vault`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication jwt required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            if (ifMatch != null) {
                localVarHeaderParameter['if-match'] = String(ifMatch);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(putVaultMetaRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * VaultApi - functional programming interface
 * @export
 */
export const VaultApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = VaultApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async exportVault(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ExportVaultResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.exportVault(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['VaultApi.exportVault']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {VaultBlobType} type 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getVaultBlob(type: VaultBlobType, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetVaultBlobResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getVaultBlob(type, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['VaultApi.getVaultBlob']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getVaultMeta(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetVaultMetaResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getVaultMeta(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['VaultApi.getVaultMeta']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {VaultExportV1} vaultExportV1 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async importVault(vaultExportV1: VaultExportV1, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ImportVaultResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.importVault(vaultExportV1, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['VaultApi.importVault']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {VaultBlobType} type 
         * @param {PutVaultBlobRequest} putVaultBlobRequest 
         * @param {string} [ifMatch] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async putVaultBlob(type: VaultBlobType, putVaultBlobRequest: PutVaultBlobRequest, ifMatch?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PutVaultBlobResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.putVaultBlob(type, putVaultBlobRequest, ifMatch, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['VaultApi.putVaultBlob']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {PutVaultMetaRequest} putVaultMetaRequest 
         * @param {string} [ifMatch] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async putVaultMeta(putVaultMetaRequest: PutVaultMetaRequest, ifMatch?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PutVaultMetaResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.putVaultMeta(putVaultMetaRequest, ifMatch, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['VaultApi.putVaultMeta']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * VaultApi - factory interface
 * @export
 */
export const VaultApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = VaultApiFp(configuration)
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        exportVault(options?: RawAxiosRequestConfig): AxiosPromise<ExportVaultResponse> {
            return localVarFp.exportVault(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {VaultApiGetVaultBlobRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getVaultBlob(requestParameters: VaultApiGetVaultBlobRequest, options?: RawAxiosRequestConfig): AxiosPromise<GetVaultBlobResponse> {
            return localVarFp.getVaultBlob(requestParameters.type, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getVaultMeta(options?: RawAxiosRequestConfig): AxiosPromise<GetVaultMetaResponse> {
            return localVarFp.getVaultMeta(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {VaultApiImportVaultRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        importVault(requestParameters: VaultApiImportVaultRequest, options?: RawAxiosRequestConfig): AxiosPromise<ImportVaultResponse> {
            return localVarFp.importVault(requestParameters.vaultExportV1, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {VaultApiPutVaultBlobRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        putVaultBlob(requestParameters: VaultApiPutVaultBlobRequest, options?: RawAxiosRequestConfig): AxiosPromise<PutVaultBlobResponse> {
            return localVarFp.putVaultBlob(requestParameters.type, requestParameters.putVaultBlobRequest, requestParameters.ifMatch, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {VaultApiPutVaultMetaRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        putVaultMeta(requestParameters: VaultApiPutVaultMetaRequest, options?: RawAxiosRequestConfig): AxiosPromise<PutVaultMetaResponse> {
            return localVarFp.putVaultMeta(requestParameters.putVaultMetaRequest, requestParameters.ifMatch, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for getVaultBlob operation in VaultApi.
 * @export
 * @interface VaultApiGetVaultBlobRequest
 */
export interface VaultApiGetVaultBlobRequest {
    /**
     * 
     * @type {VaultBlobType}
     * @memberof VaultApiGetVaultBlob
     */
    readonly type: VaultBlobType
}

/**
 * Request parameters for importVault operation in VaultApi.
 * @export
 * @interface VaultApiImportVaultRequest
 */
export interface VaultApiImportVaultRequest {
    /**
     * 
     * @type {VaultExportV1}
     * @memberof VaultApiImportVault
     */
    readonly vaultExportV1: VaultExportV1
}

/**
 * Request parameters for putVaultBlob operation in VaultApi.
 * @export
 * @interface VaultApiPutVaultBlobRequest
 */
export interface VaultApiPutVaultBlobRequest {
    /**
     * 
     * @type {VaultBlobType}
     * @memberof VaultApiPutVaultBlob
     */
    readonly type: VaultBlobType

    /**
     * 
     * @type {PutVaultBlobRequest}
     * @memberof VaultApiPutVaultBlob
     */
    readonly putVaultBlobRequest: PutVaultBlobRequest

    /**
     * 
     * @type {string}
     * @memberof VaultApiPutVaultBlob
     */
    readonly ifMatch?: string
}

/**
 * Request parameters for putVaultMeta operation in VaultApi.
 * @export
 * @interface VaultApiPutVaultMetaRequest
 */
export interface VaultApiPutVaultMetaRequest {
    /**
     * 
     * @type {PutVaultMetaRequest}
     * @memberof VaultApiPutVaultMeta
     */
    readonly putVaultMetaRequest: PutVaultMetaRequest

    /**
     * 
     * @type {string}
     * @memberof VaultApiPutVaultMeta
     */
    readonly ifMatch?: string
}

/**
 * VaultApi - object-oriented interface
 * @export
 * @class VaultApi
 * @extends {BaseAPI}
 */
export class VaultApi extends BaseAPI {
    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof VaultApi
     */
    public exportVault(options?: RawAxiosRequestConfig) {
        return VaultApiFp(this.configuration).exportVault(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {VaultApiGetVaultBlobRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof VaultApi
     */
    public getVaultBlob(requestParameters: VaultApiGetVaultBlobRequest, options?: RawAxiosRequestConfig) {
        return VaultApiFp(this.configuration).getVaultBlob(requestParameters.type, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof VaultApi
     */
    public getVaultMeta(options?: RawAxiosRequestConfig) {
        return VaultApiFp(this.configuration).getVaultMeta(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {VaultApiImportVaultRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof VaultApi
     */
    public importVault(requestParameters: VaultApiImportVaultRequest, options?: RawAxiosRequestConfig) {
        return VaultApiFp(this.configuration).importVault(requestParameters.vaultExportV1, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {VaultApiPutVaultBlobRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof VaultApi
     */
    public putVaultBlob(requestParameters: VaultApiPutVaultBlobRequest, options?: RawAxiosRequestConfig) {
        return VaultApiFp(this.configuration).putVaultBlob(requestParameters.type, requestParameters.putVaultBlobRequest, requestParameters.ifMatch, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {VaultApiPutVaultMetaRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof VaultApi
     */
    public putVaultMeta(requestParameters: VaultApiPutVaultMetaRequest, options?: RawAxiosRequestConfig) {
        return VaultApiFp(this.configuration).putVaultMeta(requestParameters.putVaultMetaRequest, requestParameters.ifMatch, options).then((request) => request(this.axios, this.basePath));
    }
}



