// Contracts for check-prisma-migrations.mjs, following
// check-nx-declared-targets.test.mjs's shape: the checker runs as a real
// subprocess against a miniature migrations tree, because the fact it asserts
// is a fact about files on disk (ADR 0085).
//
// Every test here is one of the drift directions the checker's header claims
// to catch, plus the exit-2 cases that say the check could not run at all.
import assert from 'node:assert/strict';
import { spawnSync } from 'node:child_process';
import { mkdirSync, mkdtempSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join } from 'node:path';
import test from 'node:test';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = join(HERE, '..', '..');
const CHECKER = join(HERE, 'check-prisma-migrations.mjs');

const MIGRATIONS = 'migrations';
const SCHEMA = 'schema';

function createWorkspace(t) {
  const workspace = mkdtempSync(join(tmpdir(), 'prisma-migrations-'));
  t.after(() => rmSync(workspace, { recursive: true, force: true }));
  return workspace;
}

function write(workspace, relative, contents) {
  const path = join(workspace, relative);
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, contents);
}

function writeMigration(
  workspace,
  name,
  sql = 'ALTER TABLE "User" ADD "x" TEXT;',
) {
  write(workspace, join(MIGRATIONS, name, 'migration.sql'), sql);
}

function writeLock(workspace, provider = 'postgresql') {
  write(
    workspace,
    join(MIGRATIONS, 'migration_lock.toml'),
    `# Please do not edit this file manually\nprovider = "${provider}"\n`,
  );
}

function writeSchema(workspace, provider = 'postgres') {
  write(
    workspace,
    join(SCHEMA, 'schema.prisma'),
    `datasource db {\n  provider = "${provider}"\n}\n`,
  );
}

/** A workspace with one valid migration, a lock file, and a schema. */
function scaffold(t) {
  const workspace = createWorkspace(t);
  writeMigration(workspace, '20260101000000_init');
  writeLock(workspace);
  writeSchema(workspace);
  return workspace;
}

const run = (workspace, ...args) =>
  spawnSync(process.execPath, [CHECKER, MIGRATIONS, SCHEMA, ...args], {
    cwd: workspace,
    encoding: 'utf8',
  });

test('exits 0 against the real repository', () => {
  const result = spawnSync(process.execPath, [CHECKER], {
    cwd: REPO_ROOT,
    encoding: 'utf8',
  });
  assert.equal(result.status, 0, `${result.stdout}\n${result.stderr}`);
  assert.match(result.stdout, /migration\(s\) well-formed/);
});

test('passes a well-formed history', (t) => {
  const result = run(scaffold(t));
  assert.equal(result.status, 0, `${result.stdout}\n${result.stderr}`);
  assert.match(result.stdout, /1 migration\(s\) well-formed/);
});

test('accepts the schema spelling "postgres" against a lock file spelling "postgresql"', (t) => {
  const workspace = createWorkspace(t);
  writeMigration(workspace, '20260101000000_init');
  writeLock(workspace, 'postgresql');
  writeSchema(workspace, 'postgres');
  assert.equal(run(workspace).status, 0);
});

test('fails a migration directory that is not <timestamp>_<snake_slug>', (t) => {
  const workspace = scaffold(t);
  writeMigration(workspace, 'add_something');
  const result = run(workspace);
  assert.equal(result.status, 1);
  assert.match(
    result.stderr,
    /add_something\n\s+name is not <14-digit timestamp>/,
  );
});

test('fails a migration directory whose slug is not lowercase snake case', (t) => {
  const workspace = scaffold(t);
  writeMigration(workspace, '20260202000000_AddThing');
  const result = run(workspace);
  assert.equal(result.status, 1);
  assert.match(result.stderr, /20260202000000_AddThing/);
});

test('fails two migrations sharing a timestamp', (t) => {
  const workspace = scaffold(t);
  writeMigration(workspace, '20260303000000_branch_a');
  writeMigration(workspace, '20260303000000_branch_b');
  const result = run(workspace);
  assert.equal(result.status, 1);
  assert.match(
    result.stderr,
    /20260303000000\n\s+is the timestamp of 2 migrations/,
  );
});

test('fails a migration directory with no migration.sql', (t) => {
  const workspace = scaffold(t);
  mkdirSync(join(workspace, MIGRATIONS, '20260404000000_empty_dir'));
  const result = run(workspace);
  assert.equal(result.status, 1);
  assert.match(result.stderr, /carries no migration\.sql/);
});

test('fails a migration.sql that is empty', (t) => {
  const workspace = scaffold(t);
  writeMigration(workspace, '20260505000000_blank', '\n  \n');
  const result = run(workspace);
  assert.equal(result.status, 1);
  assert.match(
    result.stderr,
    /holds no statement once SQL comments are stripped/,
  );
});

test('fails a migration.sql that holds only comments', (t) => {
  const workspace = scaffold(t);
  writeMigration(
    workspace,
    '20260606000000_only_comments',
    '-- TODO: write the migration\n/* not yet */\n',
  );
  const result = run(workspace);
  assert.equal(result.status, 1);
  assert.match(
    result.stderr,
    /holds no statement once SQL comments are stripped/,
  );
});

test('accepts a migration.sql whose statement is preceded by comments', (t) => {
  const workspace = createWorkspace(t);
  writeMigration(
    workspace,
    '20260101000000_init',
    '-- CreateTable\nCREATE TABLE "User" ("id" TEXT NOT NULL);\n',
  );
  writeLock(workspace);
  writeSchema(workspace);
  assert.equal(run(workspace).status, 0);
});

test('fails a second .sql file the engine would never read', (t) => {
  const workspace = scaffold(t);
  writeMigration(workspace, '20260707000000_two_files');
  write(
    workspace,
    join(MIGRATIONS, '20260707000000_two_files', 'rollback.sql'),
    'DROP TABLE "User";',
  );
  const result = run(workspace);
  assert.equal(result.status, 1);
  assert.match(
    result.stderr,
    /rollback\.sql\n\s+is SQL the engine never reads/,
  );
});

test('fails a stray file beside the migration directories', (t) => {
  const workspace = scaffold(t);
  write(workspace, join(MIGRATIONS, 'notes.md'), 'scratch');
  const result = run(workspace);
  assert.equal(result.status, 1);
  assert.match(result.stderr, /notes\.md\n\s+is a file/);
});

test('fails a missing migration_lock.toml', (t) => {
  const workspace = createWorkspace(t);
  writeMigration(workspace, '20260101000000_init');
  writeSchema(workspace);
  const result = run(workspace);
  assert.equal(result.status, 1);
  assert.match(result.stderr, /migration_lock\.toml\n\s+is missing/);
});

test('fails a lock-file provider that disagrees with the schema', (t) => {
  const workspace = createWorkspace(t);
  writeMigration(workspace, '20260101000000_init');
  writeLock(workspace, 'mysql');
  writeSchema(workspace, 'postgres');
  const result = run(workspace);
  assert.equal(result.status, 1);
  assert.match(result.stderr, /records provider "mysql".*declares "postgres"/s);
});

test('exits 2 when the migrations directory does not exist', (t) => {
  const workspace = createWorkspace(t);
  writeSchema(workspace);
  const result = run(workspace);
  assert.equal(result.status, 2);
  assert.match(result.stderr, /not found/);
});

test('exits 2 when the schema declares no datasource', (t) => {
  const workspace = createWorkspace(t);
  writeMigration(workspace, '20260101000000_init');
  writeLock(workspace);
  write(workspace, join(SCHEMA, 'schema.prisma'), 'generator client {\n}\n');
  const result = run(workspace);
  assert.equal(result.status, 2);
  assert.match(result.stderr, /no datasource block with a provider found/);
});

test('exits 2 when the history holds no migrations at all', (t) => {
  const workspace = createWorkspace(t);
  writeLock(workspace);
  writeSchema(workspace);
  const result = run(workspace);
  assert.equal(result.status, 2);
  assert.match(result.stderr, /no migration directories found/);
});

test('--print lists the migrations and both providers', (t) => {
  const result = run(scaffold(t), '--print');
  assert.equal(result.status, 0);
  assert.match(result.stdout, /20260101000000_init/);
  assert.match(result.stdout, /migration_lock\.toml: postgresql/);
  assert.match(result.stdout, /schema datasource: postgres/);
});
