// @ts-check
/**
 * Style Dictionary build script.
 *
 * Reads libs/design-tokens/src/tokens.json (W3C DTCG format) and emits:
 *   - src/generated/tokens.css      Brand Primitive custom properties on :root
 *   - src/generated/tokens.ts       Typed TS constants for the primitive tier
 *   - src/generated/roles.css       Semantic Role variables for :root and .dark
 *   - src/generated/roles.ts        The same roles as TS maps, one per colour mode
 *
 * The primitive tier is what the landing page and the email shell consume
 * directly. `roles.css` is what the web application stylesheet imports; every
 * Tailwind colour utility resolves through it. See ADR 0065.
 *
 * `roles.ts` exists because the Mobile App has no stylesheet to resolve a CSS
 * variable through, and a role — not a primitive — is what a theme is made of:
 * a primitive has one value, and a mobile theme needs the pair. The two maps
 * are emitted from the same tokens as the CSS, so light and dark cannot drift
 * apart in the one place that reads them as data.
 *
 * Run via:  nx run design-tokens:build-tokens
 */
const path = require('node:path');
const StyleDictionary = require('style-dictionary').default;

const SRC_DIR = path.join(__dirname, '..', 'src');
const OUT_DIR = path.join(SRC_DIR, 'generated');

/** kebab-case path joiner, e.g. ['color','primary'] -> 'color-primary' */
const kebab = (parts) => parts.join('-');

/** CamelCase TS identifier, e.g. ['color','primary'] -> 'colorPrimary' */
const camel = (parts) =>
  parts
    .map((p, i) =>
      i === 0
        ? p.replace(/[-_]([a-z0-9])/g, (_, c) => c.toUpperCase())
        : p
            .replace(/[-_]([a-z0-9])/g, (_, c) => c.toUpperCase())
            .replace(/^./, (c) => c.toUpperCase()),
    )
    .join('');

/**
 * A Semantic Role value -> the bare triple shadcn-style configs wrap in `hsl()`.
 * Emitting a triple rather than a full colour keeps both Tailwind configs unchanged.
 *
 * Two input shapes, because the `css` transform group normalises a colour to a
 * 6-digit hex when it is opaque and to `rgba(...)` when it is not. Only the
 * scrim role is translucent, and it is translucent by definition — a scrim is a
 * wash over what is behind it — so this has to carry alpha rather than reject
 * it. `H S% L% / A` is the same syntax `hsl()` already accepts.
 */
const parseColor = (value) => {
  const text = String(value).trim();
  const hex = /^#?([\da-f]{2})([\da-f]{2})([\da-f]{2})([\da-f]{2})?$/i.exec(
    text,
  );
  if (hex) {
    const [r, g, b] = hex.slice(1, 4).map((c) => parseInt(c, 16) / 255);
    return {
      r,
      g,
      b,
      a: hex[4] === undefined ? 1 : parseInt(hex[4], 16) / 255,
    };
  }
  const rgb =
    /^rgba?\(\s*([\d.]+)\s*,\s*([\d.]+)\s*,\s*([\d.]+)\s*(?:,\s*([\d.]+)\s*)?\)$/i.exec(
      text,
    );
  if (rgb) {
    const [r, g, b] = rgb.slice(1, 4).map((c) => parseFloat(c) / 255);
    return { r, g, b, a: rgb[4] === undefined ? 1 : parseFloat(rgb[4]) };
  }
  return null;
};

const hslTriple = (value) => {
  const parsed = parseColor(value);
  if (!parsed)
    throw new Error(
      `Semantic Role value must be a hex or rgb(a) colour, got: ${value}`,
    );
  const { r, g, b, a } = parsed;
  const max = Math.max(r, g, b);
  const min = Math.min(r, g, b);
  const l = (max + min) / 2;
  const d = max - min;
  let h = 0;
  let sat = 0;
  if (d !== 0) {
    sat = d / (1 - Math.abs(2 * l - 1));
    if (max === r) h = ((g - b) / d) % 6;
    else if (max === g) h = (b - r) / d + 2;
    else h = (r - g) / d + 4;
    h *= 60;
    if (h < 0) h += 360;
  }
  const round = (n) => Math.round(n * 10) / 10;
  const triple = `${round(h)} ${round(sat * 100)}% ${round(l * 100)}%`;
  return a === 1 ? triple : `${triple} / ${Math.round(a * 1000) / 1000}`;
};

// --- Custom formats ------------------------------------------------------

StyleDictionary.registerFormat({
  name: 'mo/css-variables',
  format: ({ dictionary }) => {
    const lines = dictionary.allTokens.map(
      (t) => `  --${kebab(t.path)}: ${t.$value ?? t.value};`,
    );
    return [
      '/* AUTO-GENERATED by libs/design-tokens — do not edit by hand. */',
      ':root {',
      ...lines,
      '}',
      '',
    ].join('\n');
  },
});

StyleDictionary.registerFormat({
  name: 'mo/ts-constants',
  format: ({ dictionary }) => {
    const entries = dictionary.allTokens.map((t) => {
      const id = camel(t.path);
      const value = JSON.stringify(t.$value ?? t.value);
      const cssVar = `--${kebab(t.path)}`;
      const description = t.$description ?? t.description ?? '';
      const doc = description
        ? `/** ${description.replace(/\*\//g, '*\\/')} */\n`
        : '';
      return `${doc}export const ${id} = ${value};\nexport const ${id}Var = 'var(${cssVar})';`;
    });
    const tokenObj = dictionary.allTokens
      .map(
        (t) =>
          `  '${kebab(t.path)}': { value: ${JSON.stringify(
            t.$value ?? t.value,
          )}, cssVar: 'var(--${kebab(t.path)})' }`,
      )
      .join(',\n');
    return [
      '// AUTO-GENERATED by libs/design-tokens — do not edit by hand.',
      ...entries,
      '',
      'export const tokens = {',
      tokenObj,
      '} as const;',
      '',
      'export type TokenName = keyof typeof tokens;',
      '',
    ].join('\n');
  },
});

StyleDictionary.registerFormat({
  name: 'mo/role-variables',
  format: ({ dictionary, options }) => {
    const byMode = { light: [], dark: [] };
    for (const t of dictionary.allTokens) {
      const [, mode, ...rest] = t.path;
      if (!byMode[mode]) continue;
      byMode[mode].push(
        `  --${kebab(rest)}: ${hslTriple(t.$value ?? t.value)};`,
      );
    }
    return [
      '/* AUTO-GENERATED by libs/design-tokens — do not edit by hand. */',
      '/*',
      ' * Semantic Roles. Values are bare HSL triples because the Tailwind configs',
      ' * wrap them as hsl(var(--role)); see ADR 0065.',
      ' */',
      '@layer base {',
      '  :root {',
      ...byMode.light.map((l) => `  ${l}`),
      `    --radius: ${options.radius};`,
      '  }',
      '',
      '  .dark {',
      ...byMode.dark.map((l) => `  ${l}`),
      '  }',
      '}',
      '',
    ].join('\n');
  },
});

StyleDictionary.registerFormat({
  name: 'mo/ts-roles',
  format: ({ dictionary }) => {
    const byMode = { light: [], dark: [] };
    for (const t of dictionary.allTokens) {
      const [, mode, ...rest] = t.path;
      if (!byMode[mode]) continue;
      byMode[mode].push(
        `  ${camel(rest)}: ${JSON.stringify(t.$value ?? t.value)},`,
      );
    }
    return [
      '// AUTO-GENERATED by libs/design-tokens — do not edit by hand.',
      '',
      '/** Every Semantic Role, resolved for the light colour mode. */',
      'export const roleLight = {',
      ...byMode.light,
      '} as const;',
      '',
      '/**',
      ' * Every Semantic Role, resolved for the dark colour mode.',
      ' *',
      ' * The `satisfies` is the point of this file: a role present in one mode',
      ' * and absent from the other fails the build here rather than rendering',
      ' * as `undefined` on one device.',
      ' */',
      'export const roleDark = {',
      ...byMode.dark,
      '} as const satisfies Record<keyof typeof roleLight, string>;',
      '',
      '/** The name of a Semantic Role — the same set in both colour modes. */',
      'export type SemanticRoleName = keyof typeof roleLight;',
      '',
    ].join('\n');
  },
});

// --- Build ---------------------------------------------------------------

/** The primitive tier — everything the semantic tier is built out of. */
const isPrimitive = (token) => token.path[0] !== 'mode';
/** The semantic tier — one entry per Semantic Role per colour mode. */
const isRole = (token) => token.path[0] === 'mode';

async function run() {
  const tokens = require(path.join(SRC_DIR, 'tokens.json'));

  const sd = new StyleDictionary({
    source: [path.join(SRC_DIR, 'tokens.json')],
    log: { verbosity: 'silent' },
    platforms: {
      css: {
        transformGroup: 'css',
        buildPath: OUT_DIR + '/',
        files: [
          {
            destination: 'tokens.css',
            format: 'mo/css-variables',
            filter: isPrimitive,
          },
        ],
      },
      ts: {
        // The `js` transform group, with its `color/hex` swapped for
        // `color/css`. `color/hex` calls `toHexString()`, which silently drops
        // alpha — it would emit the scrim primitive as an opaque `#030711`,
        // a constant that says the opposite of what the token means. For
        // every opaque colour the two transforms agree, so this changes one
        // token's output and nothing else's.
        transforms: ['attribute/cti', 'name/camel', 'size/rem', 'color/css'],
        buildPath: OUT_DIR + '/',
        files: [
          {
            destination: 'tokens.ts',
            format: 'mo/ts-constants',
            filter: isPrimitive,
          },
        ],
      },
      roles: {
        transformGroup: 'css',
        buildPath: OUT_DIR + '/',
        files: [
          {
            destination: 'roles.css',
            format: 'mo/role-variables',
            filter: isRole,
            options: { radius: tokens.radius.md.$value },
          },
          {
            destination: 'roles.ts',
            format: 'mo/ts-roles',
            filter: isRole,
          },
        ],
      },
    },
  });

  await sd.buildAllPlatforms();
  // eslint-disable-next-line no-console
  console.log(
    'design-tokens: generated primitive CSS/TS and Semantic Role CSS/TS.',
  );
}

// Exported so the pure parts can be tested without running a build.
module.exports = { hslTriple, kebab, camel, isPrimitive, isRole };

if (require.main === module) {
  run().catch((err) => {
    console.error(err);
    process.exit(1);
  });
}
