// @ts-check
/**
 * Style Dictionary build script.
 *
 * Reads libs/design-tokens/src/tokens.json (W3C DTCG format) and emits:
 *   - src/generated/tokens.css      CSS custom properties on :root
 *   - src/generated/tokens.ts       Typed TS constants
 *   - src/generated/tailwind-preset.js  Tailwind 3/4 preset
 *
 * Run via:  nx run design-tokens:build-tokens
 */
const path = require('node:path');
const StyleDictionary = require('style-dictionary').default;

const SRC_DIR = path.join(__dirname, '..', 'src');
const OUT_DIR = path.join(SRC_DIR, 'generated');

/** kebab-case path joiner, e.g. ['color','primary'] -> 'color-primary' */
const kebab = (parts) => parts.join('-');

/** CamelCase TS identifier, e.g. ['color','primary'] -> 'colorPrimary' */
const camel = (parts) =>
  parts
    .map((p, i) =>
      i === 0
        ? p.replace(/[-_]([a-z0-9])/g, (_, c) => c.toUpperCase())
        : p
            .replace(/[-_]([a-z0-9])/g, (_, c) => c.toUpperCase())
            .replace(/^./, (c) => c.toUpperCase()),
    )
    .join('');

// --- Custom formats ------------------------------------------------------

StyleDictionary.registerFormat({
  name: 'mo/css-variables',
  format: ({ dictionary }) => {
    const lines = dictionary.allTokens.map(
      (t) => `  --${kebab(t.path)}: ${t.$value ?? t.value};`,
    );
    return [
      '/* AUTO-GENERATED by libs/design-tokens — do not edit by hand. */',
      ':root {',
      ...lines,
      '}',
      '',
    ].join('\n');
  },
});

StyleDictionary.registerFormat({
  name: 'mo/ts-constants',
  format: ({ dictionary }) => {
    const entries = dictionary.allTokens.map((t) => {
      const id = camel(t.path);
      const value = JSON.stringify(t.$value ?? t.value);
      const cssVar = `--${kebab(t.path)}`;
      const description = t.$description ?? t.description ?? '';
      const doc = description
        ? `/** ${description.replace(/\*\//g, '*\\/')} */\n`
        : '';
      return `${doc}export const ${id} = ${value};\nexport const ${id}Var = 'var(${cssVar})';`;
    });
    const tokenObj = dictionary.allTokens
      .map(
        (t) =>
          `  '${kebab(t.path)}': { value: ${JSON.stringify(
            t.$value ?? t.value,
          )}, cssVar: 'var(--${kebab(t.path)})' }`,
      )
      .join(',\n');
    return [
      '// AUTO-GENERATED by libs/design-tokens — do not edit by hand.',
      ...entries,
      '',
      'export const tokens = {',
      tokenObj,
      '} as const;',
      '',
      'export type TokenName = keyof typeof tokens;',
      '',
    ].join('\n');
  },
});

StyleDictionary.registerFormat({
  name: 'mo/tailwind-preset',
  format: ({ dictionary }) => {
    const colors = {};
    const spacing = {};
    const radius = {};
    const fontFamily = {};
    const boxShadow = {};

    for (const t of dictionary.allTokens) {
      const [group, ...rest] = t.path;
      const key = rest.join('-');
      const value = t.$value ?? t.value;
      const cssVar = `var(--${kebab(t.path)})`;
      switch (group) {
        case 'color':
          colors[key] = cssVar;
          break;
        case 'space':
          spacing[key] = cssVar;
          break;
        case 'radius':
          radius[key] = cssVar;
          break;
        case 'font':
          // Tailwind expects an array of family strings.
          fontFamily[key] = value
            .split(',')
            .map((s) => s.trim().replace(/^['"]|['"]$/g, ''));
          break;
        case 'shadow':
          boxShadow[key] = cssVar;
          break;
        default:
          break;
      }
    }

    return [
      '// AUTO-GENERATED by libs/design-tokens — do not edit by hand.',
      '/** @type {import("tailwindcss").Config} */',
      'module.exports = {',
      '  theme: {',
      '    extend: {',
      `      colors: ${JSON.stringify(colors, null, 8)},`,
      `      spacing: ${JSON.stringify(spacing, null, 8)},`,
      `      borderRadius: ${JSON.stringify(radius, null, 8)},`,
      `      fontFamily: ${JSON.stringify(fontFamily, null, 8)},`,
      `      boxShadow: ${JSON.stringify(boxShadow, null, 8)},`,
      '    },',
      '  },',
      '};',
      '',
    ].join('\n');
  },
});

// --- Build ---------------------------------------------------------------

async function run() {
  const sd = new StyleDictionary({
    source: [path.join(SRC_DIR, 'tokens.json')],
    log: { verbosity: 'silent' },
    platforms: {
      css: {
        transformGroup: 'css',
        buildPath: OUT_DIR + '/',
        files: [{ destination: 'tokens.css', format: 'mo/css-variables' }],
      },
      ts: {
        transformGroup: 'js',
        buildPath: OUT_DIR + '/',
        files: [{ destination: 'tokens.ts', format: 'mo/ts-constants' }],
      },
      tw: {
        transformGroup: 'js',
        buildPath: OUT_DIR + '/',
        files: [
          { destination: 'tailwind-preset.js', format: 'mo/tailwind-preset' },
        ],
      },
    },
  });

  await sd.buildAllPlatforms();
  // eslint-disable-next-line no-console
  console.log('design-tokens: generated CSS, TS, and Tailwind preset.');
}

run().catch((err) => {
  console.error(err);
  process.exit(1);
});
