/**
 * Tests for Vault Claim by Recovery Key — what establishing and claiming on a
 * recovery key looks like, why wrong keys and empty devices are one answer, and
 * why ownership is never replaced without the User's express consent.
 *
 * Tests use REAL WebCrypto to unwrap Master Keys, not stubs. A recovery key is
 * generated by the implementation via `handle.initialize()`, and tests that use
 * one minted by a separate `initialize()` call establish that the unwrap is real:
 * both the wrong-key and empty-device paths do the same cryptographic work and
 * return the same value — the question of whether there was something here is
 * never answered. Strict timing equality is deliberately not asserted because it
 * would be flaky. The Master Key returned on success is verified by encrypting
 * test data to the Vault before claiming, then decrypting after claiming with
 * the returned key; reading the known plaintext proves the unwrap was real
 * rather than asserted.
 */

// === Global setup for jsdom ===
if (
  typeof (globalThis as unknown as { TextEncoder?: unknown }).TextEncoder ===
  'undefined'
) {
  const { TextEncoder, TextDecoder } = require('util');
  (globalThis as unknown as Record<string, unknown>).TextEncoder = TextEncoder;
  (globalThis as unknown as Record<string, unknown>).TextDecoder = TextDecoder;
}

// === Polyfill crypto.subtle for Node's jsdom environment ===
// eslint-disable-next-line @typescript-eslint/no-explicit-any
if (!(globalThis as any).crypto?.subtle) {
  const { webcrypto } = require('crypto');
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  if (!(globalThis as any).crypto) {
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    (globalThis as any).crypto = {};
  }
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  (globalThis as any).crypto.subtle = webcrypto.subtle;
}

import { claimUnclaimedLocalVaultWithRecoveryKey } from './vaultClaimEvidence';
import {
  VAULT_STORAGE_KEY,
  LOCAL_VAULT_RECORD_VERSION,
  localVaultStorageKey,
  type VaultStorageV1,
} from './localVaultStorage';
import { createVaultHandle, VaultSecretMismatchError } from './vaultHandle';
import {
  LocalVaultAlreadyOwnedError,
  NoUnclaimedLocalVaultError,
} from './localVaultAccess';

type UnclaimedVaultFixture = {
  vault: VaultStorageV1;
  raw: string;
  recoveryKey: string;
};

/**
 * Helper to get a localStorage value, throwing if the key is missing.
 */
function getRequiredLocalStorageItem(key: string): string {
  const value = localStorage.getItem(key);
  if (value === null) {
    throw new Error(`Required localStorage key "${key}" is missing`);
  }
  return value;
}

/**
 * Put a real, WebCrypto-built Vault into the unsuffixed slot as an Unclaimed Local Vault,
 * and return the recovery key that can unwrap it.
 * Uses a throwaway owner distinct from the test owner so no per-User key is left behind.
 */
async function seedUnclaimedLocalVaultWithRecoveryKey(
  passphrase: string,
): Promise<UnclaimedVaultFixture> {
  const throwawayOwner = `throwaway-${Math.random().toString(36).slice(2)}`;
  const handle = createVaultHandle({ owner: throwawayOwner });
  const { recoveryKey } = await handle.initialize({ passphrase });

  const vault = handle.loadVault();
  if (!vault) {
    throw new Error('Failed to load vault after initialize');
  }

  const ownedKey = localVaultStorageKey(throwawayOwner);
  const ownedRaw = getRequiredLocalStorageItem(ownedKey);
  const ownedRecord = JSON.parse(ownedRaw);

  localStorage.removeItem(ownedKey);
  const raw = JSON.stringify(ownedRecord.vault);
  localStorage.setItem(VAULT_STORAGE_KEY, raw);

  return { vault: ownedRecord.vault, raw, recoveryKey };
}

/**
 * Helper to snapshot all localStorage entries for byte-identity assertions.
 */
function snapshotLocalStorage(): Map<string, string | null> {
  const snapshot = new Map<string, string | null>();
  for (const key of Object.keys(localStorage)) {
    snapshot.set(key, localStorage.getItem(key));
  }
  return snapshot;
}

/**
 * Helper to verify all localStorage entries are byte-identical to a snapshot.
 */
function assertStorageByteIdentical(
  before: Map<string, string | null>,
  after: Map<string, string | null>,
) {
  const allKeys = new Set([...before.keys(), ...after.keys()]);
  for (const key of allKeys) {
    expect(after.get(key)).toBe(before.get(key));
  }
}

beforeEach(() => {
  localStorage.clear();
  jest.clearAllMocks();
});

describe('claimUnclaimedLocalVaultWithRecoveryKey', () => {
  const testPassphrase = 'testpass123';
  const testOwner = 'test-user-id';

  test('should claim the Unclaimed Local Vault when correct recovery key is provided', async () => {
    const fixture =
      await seedUnclaimedLocalVaultWithRecoveryKey(testPassphrase);
    const handle = createVaultHandle({ owner: testOwner });

    // Before: status is unclaimed
    expect(handle.vaultStatus()).toBe('unclaimed');

    // Claim with correct recovery key
    const result = await claimUnclaimedLocalVaultWithRecoveryKey({
      handle,
      recoveryKey: fixture.recoveryKey,
    });

    // Result includes claimed status and masterKeyBytes
    expect(result.kind).toBe('claimed');
    expect(result).toHaveProperty('masterKeyBytes');
    if (result.kind === 'claimed') {
      expect(result.masterKeyBytes).toBeInstanceOf(Uint8Array);
    }

    // After: status is owned
    expect(handle.vaultStatus()).toBe('owned');

    // Verify ownership recorded in per-User key
    const ownedKey = localVaultStorageKey(testOwner);
    const ownedRaw = localStorage.getItem(ownedKey);
    expect(ownedRaw).not.toBeNull();
    // eslint-disable-next-line @typescript-eslint/no-non-null-assertion
    const ownedRecord = JSON.parse(ownedRaw!);
    expect(ownedRecord.version).toBe(LOCAL_VAULT_RECORD_VERSION);
    expect(ownedRecord.owner).toBe(testOwner);
    expect(ownedRecord.vault).toEqual(fixture.vault);

    // Verify unsuffixed slot is byte-identical (Unclaimed Vault never removed)
    const unclaimedRaw = localStorage.getItem(VAULT_STORAGE_KEY);
    expect(unclaimedRaw).toBe(fixture.raw);
  });

  test('should return Master Key that really opens the Vault', async () => {
    // Initialize a vault with test data
    const throwawayOwner = `throwaway-${Math.random().toString(36).slice(2)}`;
    const setupHandle = createVaultHandle({ owner: throwawayOwner });
    const { recoveryKey } = await setupHandle.initialize({
      passphrase: testPassphrase,
    });

    // Unlock and write test data
    await setupHandle.unlockWithPassphrase({ passphrase: testPassphrase });
    const testTodos = { items: ['test-todo-1', 'test-todo-2'] };
    await setupHandle.saveEncryptedData({
      type: 'todos',
      value: testTodos,
    });

    // Move to unclaimed slot
    const vault = setupHandle.loadVault();
    if (!vault) throw new Error('Failed to load vault');
    const ownedKey = localVaultStorageKey(throwawayOwner);
    localStorage.removeItem(ownedKey);
    const raw = JSON.stringify(vault);
    localStorage.setItem(VAULT_STORAGE_KEY, raw);

    // Claim with recovery key
    const claimHandle = createVaultHandle({ owner: testOwner });
    const result = await claimUnclaimedLocalVaultWithRecoveryKey({
      handle: claimHandle,
      recoveryKey,
    });

    if (result.kind !== 'claimed') {
      throw new Error('Expected claimed result');
    }

    // The returned masterKeyBytes should allow decryption of the test data
    const readbackHandle = createVaultHandle({
      owner: testOwner,
      masterKeyBytes: result.masterKeyBytes,
    });

    const decrypted = await readbackHandle.loadDecryptedData({
      type: 'todos',
      defaultValue: null,
    });

    // Proves the unwrap was real: we got back exactly what we stored
    expect(decrypted).toEqual(testTodos);
  });

  test('should return no-match and write nothing when recovery key is wrong', async () => {
    const fixture =
      await seedUnclaimedLocalVaultWithRecoveryKey(testPassphrase);

    // Create a second vault and extract its recovery key to use as a "wrong" key
    const wrongKeyFixture =
      await seedUnclaimedLocalVaultWithRecoveryKey(testPassphrase);
    // Clear storage and restore first fixture
    localStorage.clear();
    localStorage.setItem(VAULT_STORAGE_KEY, fixture.raw);

    const handle = createVaultHandle({ owner: testOwner });
    const storageBefore = snapshotLocalStorage();

    expect(handle.vaultStatus()).toBe('unclaimed');

    // Claim with wrong recovery key
    const result = await claimUnclaimedLocalVaultWithRecoveryKey({
      handle,
      recoveryKey: wrongKeyFixture.recoveryKey,
    });

    // Result is no-match, nothing else
    expect(result).toEqual({ kind: 'no-match' });

    // Status unchanged
    expect(handle.vaultStatus()).toBe('unclaimed');
    expect(handle.isUnlocked).toBe(false);

    // Storage byte-identical
    const storageAfter = snapshotLocalStorage();
    assertStorageByteIdentical(storageBefore, storageAfter);
  });

  test('should return no-match and write nothing when device holds nothing', async () => {
    // Don't seed any vault — device is empty
    const handle = createVaultHandle({ owner: testOwner });
    const storageBefore = snapshotLocalStorage();

    // Use a valid-looking recovery key (base64 of 32 bytes)
    const throwawayFixture =
      await seedUnclaimedLocalVaultWithRecoveryKey(testPassphrase);
    // Clear to leave device empty
    localStorage.clear();

    const result = await claimUnclaimedLocalVaultWithRecoveryKey({
      handle,
      recoveryKey: throwawayFixture.recoveryKey,
    });

    // Result is no-match
    expect(result).toEqual({ kind: 'no-match' });

    // Storage byte-identical (was empty, remains empty)
    const storageAfter = snapshotLocalStorage();
    assertStorageByteIdentical(storageBefore, storageAfter);
  });

  test('should make wrong key and empty device indistinguishable by performing same cryptographic work', async () => {
    const fixture =
      await seedUnclaimedLocalVaultWithRecoveryKey(testPassphrase);
    const wrongKeyFixture =
      await seedUnclaimedLocalVaultWithRecoveryKey(testPassphrase);

    const decryptSpy = jest.spyOn(crypto.subtle, 'decrypt');
    try {
      // === First call: device with Unclaimed Vault + wrong key ===
      localStorage.clear();
      localStorage.setItem(VAULT_STORAGE_KEY, fixture.raw);
      const handle1 = createVaultHandle({ owner: testOwner });

      // Clear to isolate this run's calls from any other invocations
      decryptSpy.mockClear();
      const result1 = await claimUnclaimedLocalVaultWithRecoveryKey({
        handle: handle1,
        recoveryKey: wrongKeyFixture.recoveryKey,
      });
      const decryptCallsWrongKey = decryptSpy.mock.calls.length;

      // === Second call: empty device with same wrong key ===
      localStorage.clear();
      const handle2 = createVaultHandle({ owner: testOwner });

      // Clear to isolate this run's calls from any other invocations
      decryptSpy.mockClear();
      const result2 = await claimUnclaimedLocalVaultWithRecoveryKey({
        handle: handle2,
        recoveryKey: wrongKeyFixture.recoveryKey,
      });
      const decryptCallsEmpty = decryptSpy.mock.calls.length;

      // === Assertions ===
      // Results are deeply equal
      expect(result1).toEqual(result2);

      // Property key sets are identical (no field in one that's not in the other)
      expect(Object.keys(result1).sort()).toEqual(Object.keys(result2).sort());

      // Both performed crypto.subtle.decrypt work
      expect(decryptCallsWrongKey).toBeGreaterThanOrEqual(1);
      expect(decryptCallsEmpty).toBeGreaterThanOrEqual(1);
    } finally {
      decryptSpy.mockRestore();
    }
  });

  test('should return no-match and not throw when recovery key is malformed on Unclaimed Vault', async () => {
    // eslint-disable-next-line @typescript-eslint/no-unused-vars
    const _fixture =
      await seedUnclaimedLocalVaultWithRecoveryKey(testPassphrase);
    const handle = createVaultHandle({ owner: testOwner });
    const storageBefore = snapshotLocalStorage();

    const malformedKey = 'not-a-key!!!';

    const result = await claimUnclaimedLocalVaultWithRecoveryKey({
      handle,
      recoveryKey: malformedKey,
    });

    // No throw, result is no-match
    expect(result).toEqual({ kind: 'no-match' });

    // Storage unchanged
    const storageAfter = snapshotLocalStorage();
    assertStorageByteIdentical(storageBefore, storageAfter);
  });

  test('should return no-match and not throw when recovery key is malformed on empty device', async () => {
    localStorage.clear();
    const handle = createVaultHandle({ owner: testOwner });
    const storageBefore = snapshotLocalStorage();

    const malformedKey = 'not-a-key!!!';

    const result = await claimUnclaimedLocalVaultWithRecoveryKey({
      handle,
      recoveryKey: malformedKey,
    });

    // No throw, result is no-match
    expect(result).toEqual({ kind: 'no-match' });

    // Storage unchanged
    const storageAfter = snapshotLocalStorage();
    assertStorageByteIdentical(storageBefore, storageAfter);
  });

  test('should yield identical results when recovery key is malformed on both devices', async () => {
    const fixture =
      await seedUnclaimedLocalVaultWithRecoveryKey(testPassphrase);
    const malformedKey = 'not-a-key!!!';

    // First: device with Unclaimed Vault
    localStorage.clear();
    localStorage.setItem(VAULT_STORAGE_KEY, fixture.raw);
    const handle1 = createVaultHandle({ owner: testOwner });
    const result1 = await claimUnclaimedLocalVaultWithRecoveryKey({
      handle: handle1,
      recoveryKey: malformedKey,
    });

    // Second: empty device
    localStorage.clear();
    const handle2 = createVaultHandle({ owner: testOwner });
    const result2 = await claimUnclaimedLocalVaultWithRecoveryKey({
      handle: handle2,
      recoveryKey: malformedKey,
    });

    // Results are identical
    expect(result1).toEqual(result2);
    expect(Object.keys(result1).sort()).toEqual(Object.keys(result2).sort());
  });

  test('should return no-match and not claim when passphrase is used instead of recovery key', async () => {
    // eslint-disable-next-line @typescript-eslint/no-unused-vars
    const _fixture =
      await seedUnclaimedLocalVaultWithRecoveryKey(testPassphrase);
    const handle = createVaultHandle({ owner: testOwner });
    const storageBefore = snapshotLocalStorage();

    // Attempt to claim using the passphrase instead of the recovery key
    const result = await claimUnclaimedLocalVaultWithRecoveryKey({
      handle,
      recoveryKey: testPassphrase, // Wrong: this is the passphrase, not the key
    });

    // Result is no-match, not claimed
    expect(result).toEqual({ kind: 'no-match' });

    // Status unchanged
    expect(handle.vaultStatus()).toBe('unclaimed');
    expect(handle.isUnlocked).toBe(false);

    // Storage byte-identical
    const storageAfter = snapshotLocalStorage();
    assertStorageByteIdentical(storageBefore, storageAfter);
  });

  test('should offer a replace rather than claim when the recovery key matches while User already holds their own Local Vault', async () => {
    // When an owner is already owned AND the recovery key matches the coexisting
    // unclaimed vault, the function returns a replace-offer. The key proves
    // evidence but MUST NOT write anything — a correct recovery key while owned
    // is an offer to replace, never the replacement itself.
    const ownHandle = createVaultHandle({ owner: testOwner });
    await ownHandle.initialize({ passphrase: testPassphrase });

    // Create an Unclaimed Vault with different passphrase
    const unclaimedFixture =
      await seedUnclaimedLocalVaultWithRecoveryKey('different-pass');

    // Now testOwner's handle should see both their own vault and the unclaimed one
    const claimHandle = createVaultHandle({ owner: testOwner });
    expect(claimHandle.vaultStatus()).toBe('owned');
    expect(claimHandle.hasUnclaimedLocalVault()).toBe(true);

    const storageBefore = snapshotLocalStorage();

    // Attempt to claim with the correct recovery key for the Unclaimed Vault
    const result = await claimUnclaimedLocalVaultWithRecoveryKey({
      handle: claimHandle,
      recoveryKey: unclaimedFixture.recoveryKey,
    });

    // Result is replace-offer, not a claim
    expect(result).toEqual({ kind: 'replace-offer' });

    // Status unchanged
    expect(claimHandle.vaultStatus()).toBe('owned');
    expect(claimHandle.isUnlocked).toBe(false);

    // Storage byte-identical: this is the load-bearing invariant — a correct
    // recovery key while owned proves evidence but MUST NOT write.
    const storageAfter = snapshotLocalStorage();
    assertStorageByteIdentical(storageBefore, storageAfter);
  });

  test('should return skipped-already-owned when owner holds owned vault with no unclaimed vault and correct recovery key is provided', async () => {
    // When an owner is already owned AND there is NO separate unclaimed vault
    // on the device, the function pays the decoy recovery unwrap cost and
    // returns skipped-already-owned. Nothing is written.
    localStorage.clear();
    jest.clearAllMocks();

    const ownHandle = createVaultHandle({ owner: testOwner });
    await ownHandle.initialize({ passphrase: testPassphrase });

    // Do NOT create an unclaimed vault — just leave the unsuffixed slot empty.
    // But we still need a valid-looking recovery key to try.
    const { recoveryKey } =
      await seedUnclaimedLocalVaultWithRecoveryKey('different-pass');

    // Remove the unclaimed vault to ensure this owner is owned-only
    localStorage.removeItem(VAULT_STORAGE_KEY);

    const claimHandle = createVaultHandle({ owner: testOwner });
    expect(claimHandle.vaultStatus()).toBe('owned');
    expect(claimHandle.hasUnclaimedLocalVault()).toBe(false);

    const storageBefore = snapshotLocalStorage();

    // Attempt to claim with a recovery key (but there's nothing to claim)
    const result = await claimUnclaimedLocalVaultWithRecoveryKey({
      handle: claimHandle,
      recoveryKey,
    });

    // Result is skipped-already-owned
    expect(result).toEqual({ kind: 'skipped-already-owned' });

    // Status unchanged
    expect(claimHandle.vaultStatus()).toBe('owned');
    expect(claimHandle.isUnlocked).toBe(false);

    // Storage byte-identical
    const storageAfter = snapshotLocalStorage();
    assertStorageByteIdentical(storageBefore, storageAfter);
  });

  test('should return no-match and write nothing when entry names different owner', async () => {
    const fixture =
      await seedUnclaimedLocalVaultWithRecoveryKey(testPassphrase);

    // Write a record under testOwner's key but naming a different owner
    const differentOwner = 'other-user-id';
    const wrongOwnerRecord = {
      version: LOCAL_VAULT_RECORD_VERSION,
      owner: differentOwner,
      vault: fixture.vault,
    };
    localStorage.setItem(
      localVaultStorageKey(testOwner),
      JSON.stringify(wrongOwnerRecord),
    );

    const handle = createVaultHandle({ owner: testOwner });
    expect(handle.vaultStatus()).toBe('owner-mismatch');

    const storageBefore = snapshotLocalStorage();

    // Attempt to claim with the recovery key
    const result = await claimUnclaimedLocalVaultWithRecoveryKey({
      handle,
      recoveryKey: fixture.recoveryKey,
    });

    // Result is no-match
    expect(result).toEqual({ kind: 'no-match' });

    // Storage byte-identical
    const storageAfter = snapshotLocalStorage();
    assertStorageByteIdentical(storageBefore, storageAfter);
  });
});

/**
 * Tests for the new claimUnclaimedLocalVaultByRecoveryKey method (AC #6).
 *
 * This method replaces the old route where unlockWithRecoveryKey implicitly
 * claimed an unclaimed Vault. The new method:
 * - Guards that the caller does NOT already own a Vault
 * - Reads slot.readUnclaimed()
 * - Unwraps the recovery-key-wrapped Master Key FIRST
 * - Then slot.claim(vault) and binds the Master Key
 * - On wrong key: throws VaultSecretMismatchError('recovery-key') and leaves storage byte-identical
 */
describe('claimUnclaimedLocalVaultByRecoveryKey (AC #6)', () => {
  const testPassphrase = 'testpass123';
  const testOwner = 'test-user-id';

  test('6a: correct recovery key claims and binds the Master Key', async () => {
    const fixture =
      await seedUnclaimedLocalVaultWithRecoveryKey(testPassphrase);
    const handle = createVaultHandle({ owner: testOwner });

    // Before: status is unclaimed
    expect(handle.vaultStatus()).toBe('unclaimed');

    // Claim with correct recovery key using the new method
    const result = await handle.claimUnclaimedLocalVaultByRecoveryKey({
      recoveryKey: fixture.recoveryKey,
    });

    // Result includes locked success and masterKeyBytes
    expect(result).toHaveProperty('masterKeyBytes');
    expect(result.masterKeyBytes).toBeInstanceOf(Uint8Array);

    // After: status is owned
    expect(handle.vaultStatus()).toBe('owned');

    // Verify ownership recorded in per-User key
    const ownedKey = localVaultStorageKey(testOwner);
    const ownedRaw = localStorage.getItem(ownedKey);
    expect(ownedRaw).not.toBeNull();
    // eslint-disable-next-line @typescript-eslint/no-non-null-assertion
    const ownedRecord = JSON.parse(ownedRaw!);
    expect(ownedRecord.version).toBe(LOCAL_VAULT_RECORD_VERSION);
    expect(ownedRecord.owner).toBe(testOwner);
    expect(ownedRecord.vault).toEqual(fixture.vault);

    // Verify unsuffixed slot is byte-identical (Unclaimed Vault never removed)
    const unclaimedRaw = localStorage.getItem(VAULT_STORAGE_KEY);
    expect(unclaimedRaw).toBe(fixture.raw);
  });

  test('6a (extended): returned Master Key really opens the Vault', async () => {
    // Initialize a vault with test data
    const throwawayOwner = `throwaway-${Math.random().toString(36).slice(2)}`;
    const setupHandle = createVaultHandle({ owner: throwawayOwner });
    const { recoveryKey } = await setupHandle.initialize({
      passphrase: testPassphrase,
    });

    // Unlock and write test data
    await setupHandle.unlockWithPassphrase({ passphrase: testPassphrase });
    const testTodos = { items: ['test-todo-1', 'test-todo-2'] };
    await setupHandle.saveEncryptedData({
      type: 'todos',
      value: testTodos,
    });

    // Move to unclaimed slot
    const vault = setupHandle.loadVault();
    if (!vault) throw new Error('Failed to load vault');
    const ownedKey = localVaultStorageKey(throwawayOwner);
    localStorage.removeItem(ownedKey);
    const raw = JSON.stringify(vault);
    localStorage.setItem(VAULT_STORAGE_KEY, raw);

    // Claim with recovery key using new method
    const claimHandle = createVaultHandle({ owner: testOwner });
    const result = await claimHandle.claimUnclaimedLocalVaultByRecoveryKey({
      recoveryKey,
    });

    // The returned masterKeyBytes should allow decryption of the test data
    const readbackHandle = createVaultHandle({
      owner: testOwner,
      masterKeyBytes: result.masterKeyBytes,
    });

    const decrypted = await readbackHandle.loadDecryptedData({
      type: 'todos',
      defaultValue: null,
    });

    // Proves the unwrap was real: we got back exactly what we stored
    expect(decrypted).toEqual(testTodos);
  });

  test('6b: wrong recovery key throws VaultSecretMismatchError and leaves storage byte-identical', async () => {
    const fixture =
      await seedUnclaimedLocalVaultWithRecoveryKey(testPassphrase);

    // Create a second vault and extract its recovery key to use as a "wrong" key
    const wrongKeyFixture =
      await seedUnclaimedLocalVaultWithRecoveryKey(testPassphrase);
    // Clear storage and restore first fixture
    localStorage.clear();
    localStorage.setItem(VAULT_STORAGE_KEY, fixture.raw);

    const handle = createVaultHandle({ owner: testOwner });
    const storageBefore = snapshotLocalStorage();

    expect(handle.vaultStatus()).toBe('unclaimed');

    // Attempt to claim with wrong recovery key
    let thrownError: unknown;
    try {
      await handle.claimUnclaimedLocalVaultByRecoveryKey({
        recoveryKey: wrongKeyFixture.recoveryKey,
      });
    } catch (err) {
      thrownError = err;
    }

    // Must throw VaultSecretMismatchError with 'recovery-key'
    expect(thrownError).toBeInstanceOf(VaultSecretMismatchError);
    if (thrownError instanceof VaultSecretMismatchError) {
      expect(thrownError.secret).toBe('recovery-key');
    }

    // Status unchanged
    expect(handle.vaultStatus()).toBe('unclaimed');
    expect(handle.isUnlocked).toBe(false);

    // Storage byte-identical
    const storageAfter = snapshotLocalStorage();
    assertStorageByteIdentical(storageBefore, storageAfter);
  });

  test('6c: caller that already owns a Vault is refused', async () => {
    // User A creates and owns a vault
    const ownHandle = createVaultHandle({ owner: testOwner });
    await ownHandle.initialize({ passphrase: testPassphrase });

    // Create an Unclaimed Vault with different passphrase
    const unclaimedFixture =
      await seedUnclaimedLocalVaultWithRecoveryKey('different-pass');

    // Now testOwner's handle should see both their own vault and the unclaimed one
    const claimHandle = createVaultHandle({ owner: testOwner });
    expect(claimHandle.vaultStatus()).toBe('owned');
    expect(claimHandle.hasUnclaimedLocalVault()).toBe(true);

    const storageBefore = snapshotLocalStorage();

    // Attempt to claim with the recovery key using new method
    let thrownError: unknown;
    try {
      await claimHandle.claimUnclaimedLocalVaultByRecoveryKey({
        recoveryKey: unclaimedFixture.recoveryKey,
      });
    } catch (err) {
      thrownError = err;
    }

    // Must throw LocalVaultAlreadyOwnedError
    expect(thrownError).toBeInstanceOf(LocalVaultAlreadyOwnedError);

    // Status unchanged
    expect(claimHandle.vaultStatus()).toBe('owned');
    expect(claimHandle.isUnlocked).toBe(false);

    // Storage byte-identical: the guard is load-bearing
    const storageAfter = snapshotLocalStorage();
    assertStorageByteIdentical(storageBefore, storageAfter);
  });

  test('6c (extended-owned): caller already owns vault is refused; owned guard fires before unclaimed check', async () => {
    // User A creates and owns a vault
    const ownHandle = createVaultHandle({ owner: testOwner });
    await ownHandle.initialize({ passphrase: testPassphrase });

    // Don't create an unclaimed vault — device is owned-only
    const unclaimedFixture =
      await seedUnclaimedLocalVaultWithRecoveryKey('different-pass');
    // Remove the unclaimed vault to ensure this owner is owned-only
    localStorage.removeItem(VAULT_STORAGE_KEY);

    const claimHandle = createVaultHandle({ owner: testOwner });
    expect(claimHandle.vaultStatus()).toBe('owned');
    expect(claimHandle.hasUnclaimedLocalVault()).toBe(false);

    const storageBefore = snapshotLocalStorage();

    // Attempt to claim
    let thrownError: unknown;
    try {
      await claimHandle.claimUnclaimedLocalVaultByRecoveryKey({
        recoveryKey: unclaimedFixture.recoveryKey,
      });
    } catch (err) {
      thrownError = err;
    }

    // Must throw LocalVaultAlreadyOwnedError (owned guard fires before unclaimed check)
    expect(thrownError).toBeInstanceOf(LocalVaultAlreadyOwnedError);

    // Status unchanged
    expect(claimHandle.vaultStatus()).toBe('owned');
    expect(claimHandle.isUnlocked).toBe(false);

    // Storage byte-identical
    const storageAfter = snapshotLocalStorage();
    assertStorageByteIdentical(storageBefore, storageAfter);
  });

  test('6c (extended-empty): device with no owned and no unclaimed vault is refused with NoUnclaimedLocalVaultError', async () => {
    // Setup: completely empty device — no owned record for any user, no unclaimed vault
    localStorage.clear();

    // Create a valid recovery key from a separate device for the attempt
    const unclaimedFixture =
      await seedUnclaimedLocalVaultWithRecoveryKey('different-pass');
    // Remove the unclaimed vault fixture to leave device truly empty
    localStorage.removeItem(VAULT_STORAGE_KEY);

    const handle = createVaultHandle({ owner: testOwner });
    expect(handle.vaultStatus()).toBe('absent');
    expect(handle.hasUnclaimedLocalVault()).toBe(false);

    const storageBefore = snapshotLocalStorage();

    // Attempt to claim
    let thrownError: unknown;
    try {
      await handle.claimUnclaimedLocalVaultByRecoveryKey({
        recoveryKey: unclaimedFixture.recoveryKey,
      });
    } catch (err) {
      thrownError = err;
    }

    // Must throw NoUnclaimedLocalVaultError (unclaimed check fires; nothing to claim)
    expect(thrownError).toBeInstanceOf(NoUnclaimedLocalVaultError);

    // Status unchanged
    expect(handle.vaultStatus()).toBe('absent');
    expect(handle.isUnlocked).toBe(false);

    // Storage byte-identical
    const storageAfter = snapshotLocalStorage();
    assertStorageByteIdentical(storageBefore, storageAfter);
  });
});
