source 'https://rubygems.org'

# You may use http://rbenv.org/ or https://rvm.io/ to install and use this version
ruby ">= 3.1.0"

# Exclude problematic versions of cocoapods that cause build failures.
gem 'cocoapods', '>= 1.13', '!= 1.15.0', '!= 1.15.1'
# Patched release for CVE-2026-33169, CVE-2026-33170, CVE-2026-33176
gem 'activesupport', '7.2.3.1'
gem 'xcodeproj', '< 1.26.0'
# Patched release for GHSA-h8w8-99g7-qmvj, GHSA-wv3x-4vxv-whpp, GHSA-6wx8-w4f5-wwcr
gem 'concurrent-ruby', '>= 1.3.7'

# Ruby 3.4.0 removed these from the standard library.
gem 'bigdecimal'
gem 'logger'
gem 'benchmark'
gem 'mutex_m'
gem 'nkf'
