import './global.css';

export const dynamic = 'force-dynamic';

export const metadata = {
  title: 'Welcome to myorganizer',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const apiBaseUrl =
    process.env.API_BASE_URL ?? process.env.NEXT_PUBLIC_API_BASE_URL ?? '';

  const runtimeConfigJson = JSON.stringify({
    API_BASE_URL: apiBaseUrl,
  }).replace(/[<>&\u2028\u2029]/g, (c) => {
    switch (c) {
      case '<':
        return '\\u003c';
      case '>':
        return '\\u003e';
      case '&':
        return '\\u0026';
      case '\u2028':
        return '\\u2028';
      case '\u2029':
        return '\\u2029';
      default:
        return c;
    }
  });

  return (
    <html lang="en">
      <head>
        <meta name="myorganizer-api-base-url" content={apiBaseUrl} />
      </head>
      <body>
        <script
          // eslint-disable-next-line react/no-danger
          dangerouslySetInnerHTML={{
            __html: `window.__MYORGANIZER_RUNTIME__=${runtimeConfigJson};window.MYORGANIZER_RUNTIME=window.__MYORGANIZER_RUNTIME__;`,
          }}
        />
        {children}
      </body>
    </html>
  );
}
